import React from 'react'

import type { Metadata } from 'next'

import jakarta from '@/lib/fonts'
import { cn } from '@/lib/utils'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn('font-jakarta antialiased', jakarta.variable)}>
        {children}
      </body>
    </html>
  )
}
